### ISSUE TITLE
Authentication fails on CC9381-HV

### ISSUE THREAD

**Issue by dorkmatt** [HarlemSquirrel/python-vivotek#13]
This may be similar to [Home Assistant #27419](https://github.com/home-assistant/core/issues/27419)

```
$ curl -q -s "http://192.168.40.10/cgi-bin/anonymous/getparam.cgi" | head -3
system_info_modelname='CC9381-HV'
system_info_extendedmodelname='CC9381-HV'
system_info_firmwareversion='CC9381-VVTK-2.2002.13.01j'

% python3
Python 3.8.9 (default, Apr 13 2022, 08:48:06)
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
>>> from libpyvivotek import VivotekCamera
>>> cam = VivotekCamera(host='192.168.40.10', port=80, usr='root', pwd='XXX', sec_lvl='admin')
>>> print("Camera model is %s" % cam.model_name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matt/Library/Python/3.8/lib/python/site-packages/libpyvivotek/vivotek.py", line 137, in model_name
    self._model_name = self.get_param("system_info_modelname")
  File "/Users/matt/Library/Python/3.8/lib/python/site-packages/libpyvivotek/vivotek.py", line 108, in get_param
    return self.__parse_response_value(response)
  File "/Users/matt/Library/Python/3.8/lib/python/site-packages/libpyvivotek/vivotek.py", line 150, in __parse_response_value
    raise VivotekCameraError('Unauthorized. Credentials may be invalid.')
libpyvivotek.vivotek.VivotekCameraError: Unauthorized. Credentials may be invalid.
```

**Comment by HarlemSquirrel** [comment]
Is the user an admin user?

**Comment by dorkmatt** [comment]
> Is the user an admin user?

Correct

**Comment by HarlemSquirrel** [comment]
Can you try with `digest_auth=True` option?

i.e.

```py
cam = VivotekCamera(host='192.168.40.10', port=80, usr='root', pwd='XXX', sec_lvl='admin', digest_auth=True)
```

**Comment by dorkmatt** [comment]
That works and the respective Home Assistant flag also works, seems worthy to consider this closed and maybe a documentation update to note that some models only authenticate using digest?
